CREATE DATABASE IF NOT EXISTS viajero;

DROP TABLE IF EXISTS postVotes, postPhotos, posts, users, cities, states, countries ;

CREATE TABLE IF NOT EXISTS users (
	idUser CHAR(36) PRIMARY KEY DEFAULT(uuid()),
    email VARCHAR(320) UNIQUE NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL,
    avatar VARCHAR(100),
    active BOOLEAN DEFAULT false,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS countries (
	idCountry INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    active BOOLEAN DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS states (
	idState INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    idCountry INT UNSIGNED NOT NULL,
    active BOOLEAN DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCountry) REFERENCES countries(idCountry)
);

CREATE TABLE IF NOT EXISTS cities (
	idCity INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    idState INT UNSIGNED NOT NULL,
    active BOOLEAN DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idState) REFERENCES states(idState)
);

CREATE TABLE IF NOT EXISTS posts (
	idPost CHAR(36) PRIMARY KEY DEFAULT (uuid()),
    idUser CHAR(36) NOT NULL,
    title VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	idCity INT UNSIGNED NOT NULL,
    active BOOLEAN DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idUser) REFERENCES users(idUser),
    FOREIGN KEY (idCity) REFERENCES cities(idCity)
);

CREATE TABLE IF NOT EXISTS postPhotos(
	idPhoto CHAR(36) PRIMARY KEY DEFAULT(uuid()),
    idPost CHAR(36) NOT NULL,
    active BOOLEAN DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idPost) REFERENCES posts(idPost)
);

CREATE TABLE IF NOT EXISTS postVotes(
	idVote INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    value ENUM('1', '2', '3', '4', '5') NOT NULL DEFAULT '3',
    idPost CHAR(36) NOT NULL,
    idUser CHAR(36) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idPost) REFERENCES posts(idPost),
    FOREIGN KEY (idUser) REFERENCES users(idUser),
	UNIQUE KEY `votos_unicos` (`idPost`,`idUser`)
);

